### ISSUE TITLE
Non-surrogate optimization fails with KeyError

### ISSUE THREAD

**Issue by frthjf** [iraikov/dmosopt#65]
Example `debug.py` script to reproduce:
```python
import logging
import numpy as np
from dmosopt import dmosopt

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def zdt1(x):
    num_variables = len(x)
    f = np.zeros(2)
    f[0] = x[0]
    g = 1.0 + 9.0 / float(num_variables - 1) * np.sum(x[1:])
    h = 1.0 - np.sqrt(f[0] / g)
    f[1] = g * h
    return f


def obj_fun(pp):
    param_values = np.asarray([pp[k] for k in sorted(pp)])
    res = zdt1(param_values)
    logger.info(f"Iter: \t pp:{pp}, result:{res}")
    return res


def zdt1_pareto(n_points=100):
    f = np.zeros([n_points, 2])
    f[:, 0] = np.linspace(0, 1, n_points)
    f[:, 1] = 1.0 - np.sqrt(f[:, 0])
    return f


if __name__ == "__main__":
    space = {}
    for i in range(30):
        space["x%d" % (i + 1)] = [0.0, 1.0]
    problem_parameters = {}
    objective_names = ["y1", "y2"]
    dmosopt_params = {
        "opt_id": "dmosopt_zdt1",
        "obj_fun_name": "debug.obj_fun",
        "problem_parameters": problem_parameters,
        "space": space,
        "objective_names": objective_names,
        "population_size": 50,
        "num_generations": 25,
        "initial_maxiter": 10,
        "optimizer_name": "age",
        "termination_conditions": True,
        "n_initial": 3,
        "n_epochs": 4,
        "surrogate_method_name": None,
        "save": True,
        "file_path": "zdt1.h5",
    }

    dmosopt.run(dmosopt_params, verbose=True)
```
```
Traceback (most recent call last):
  File "./MultiObjectiveSurrogateOptimization/debug.py", line 64, in <module>
    dmosopt.run(dmosopt_params, verbose=True)
  File "./dmosopt/dmosopt/dmosopt.py", line 1975, in run
    distwq.run(
  File "/scratch1/08818/fg14/venvs/multiobjectivesurrogateoptimization-py3.9-scratch/lib/python3.9/site-packages/distwq.py", line 2071, in run
    fun(controller, *args)
  File "./dmosopt/dmosopt/dmosopt.py", line 1944, in dopt_ctrl
    dopt.run_epoch()
  File "./dmosopt/dmosopt/dmosopt.py", line 1137, in run_epoch
    strategy_state, strategy_value, completed_evals = self.optimizer_dict[
  File "./dmosopt/dmosopt/dmosopt.py", line 357, in update_epoch
    x_resample = result_dict["x_resample"]
KeyError: 'x_resample'
```

**Comment by iraikov** [comment]
Fixed by #68
